import Head from 'next/head';
import React from 'react';

interface Props { }

function Home(props: Props) {
    const { } = props;

    return (
        <div>
            <Head>
                <title>Inoryx | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            home
        </div>
    );
}

export default Home;
