import { Auth, Space, Typography } from '@supabase/ui';
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import { useDispatch, useSelector } from 'react-redux';
import useSWR from 'swr';
import { useAppDispatch, useAppSelector } from '../redux/hooks';
import { changeAuthValue } from '../redux/reducers/authView';
import { RootState } from '../redux/store';
import { Collapse, Divider, Menu, MenuDivider, MenuItem } from '@blueprintjs/core';
import OrganizationSideBar from '../components/OrganizationSideBar';
// import { authViewSlice } from '../redux/reducers/authView';

const Home: NextPage = (props) => {
    const dispatch = useAppDispatch();
    const handleClick = () => { };

    return (
        <div className={styles.container}>
            <button onClick={() => dispatch(changeAuthValue('sign_up'))}> click</button>
            <Head>
                <title>Inoryx</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                test
                <OrganizationSideBar />
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by
                </a>
            </footer>
        </div>
    );
};

export default Home;
